[package]
name = "rugix-admin"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
axum = { version = "0.6.19", features = ["multipart"] }
clap = { version = "4.3.17", features = ["derive"] }
futures.workspace = true
include_dir = "0.7.4"
indexmap = { version = "2.5.0", features = ["serde"] }
jiff.workspace = true
mime_guess = "2.0.5"
serde.workspace = true
serde_json.workspace = true
sidex.workspace = true
sidex-serde.workspace = true
tokio = { version = "1.29.1", features = ["full"] }
uuid = { version = "1.11.0", features = ["v4"] }

xscript.workspace = true

[build-dependencies]
sidex-build-rs.workspace = true

[lints]
workspace = true
