//! Integration tests for rugix-pki using OpenSSL to generate test certificates.

use std::process::Command;

use rugix_pki::{CmsSigner, CmsVerifier, RsaHashAlgorithm, RsaSignatureMode, SignerBuilder};

/// Test certificates and keys generated by OpenSSL.
struct TestPki {
    root_cert_pem: Vec<u8>,
    signer_cert_pem: Vec<u8>,
    signer_key_pem: Vec<u8>,
    other_root_cert_pem: Vec<u8>,
    temp_dir: tempfile::TempDir,
}

impl TestPki {
    fn new() -> Self {
        let temp_dir = tempfile::tempdir().expect("failed to create temp dir");
        let dir = temp_dir.path();

        // Generate root CA key and certificate (ECDSA P-256)
        let root_key_path = dir.join("root.key");
        let root_cert_path = dir.join("root.crt");

        let status = Command::new("openssl")
            .args([
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out",
            ])
            .arg(&root_key_path)
            .status()
            .expect("failed to generate root key");
        assert!(status.success(), "failed to generate root key");

        let status = Command::new("openssl")
            .args(["req", "-x509", "-new", "-key"])
            .arg(&root_key_path)
            .args(["-out"])
            .arg(&root_cert_path)
            .args(["-days", "3650", "-subj", "/CN=Test Root CA"])
            .status()
            .expect("failed to generate root cert");
        assert!(status.success(), "failed to generate root cert");

        // Generate signer key and certificate (signed by root)
        let signer_key_path = dir.join("signer.key");
        let signer_csr_path = dir.join("signer.csr");
        let signer_cert_path = dir.join("signer.crt");

        let status = Command::new("openssl")
            .args([
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out",
            ])
            .arg(&signer_key_path)
            .status()
            .expect("failed to generate signer key");
        assert!(status.success(), "failed to generate signer key");

        let status = Command::new("openssl")
            .args(["req", "-new", "-key"])
            .arg(&signer_key_path)
            .args(["-out"])
            .arg(&signer_csr_path)
            .args(["-subj", "/CN=Test Signer"])
            .status()
            .expect("failed to generate signer csr");
        assert!(status.success(), "failed to generate signer csr");

        let status = Command::new("openssl")
            .args(["x509", "-req", "-in"])
            .arg(&signer_csr_path)
            .args(["-CA"])
            .arg(&root_cert_path)
            .args(["-CAkey"])
            .arg(&root_key_path)
            .args(["-CAcreateserial", "-out"])
            .arg(&signer_cert_path)
            .args(["-days", "365"])
            .status()
            .expect("failed to generate signer cert");
        assert!(status.success(), "failed to generate signer cert");

        // Generate another root CA for negative testing
        let other_root_key_path = dir.join("other_root.key");
        let other_root_cert_path = dir.join("other_root.crt");

        let status = Command::new("openssl")
            .args([
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out",
            ])
            .arg(&other_root_key_path)
            .status()
            .expect("failed to generate other root key");
        assert!(status.success(), "failed to generate other root key");

        let status = Command::new("openssl")
            .args(["req", "-x509", "-new", "-key"])
            .arg(&other_root_key_path)
            .args(["-out"])
            .arg(&other_root_cert_path)
            .args(["-days", "3650", "-subj", "/CN=Other Root CA"])
            .status()
            .expect("failed to generate other root cert");
        assert!(status.success(), "failed to generate other root cert");

        let root_cert_pem = std::fs::read(&root_cert_path).expect("failed to read root cert");
        let signer_cert_pem = std::fs::read(&signer_cert_path).expect("failed to read signer cert");
        let signer_key_pem = std::fs::read(&signer_key_path).expect("failed to read signer key");
        let other_root_cert_pem =
            std::fs::read(&other_root_cert_path).expect("failed to read other root cert");

        Self {
            root_cert_pem,
            signer_cert_pem,
            signer_key_pem,
            other_root_cert_pem,
            temp_dir,
        }
    }
}

#[test]
fn test_sign_and_verify() {
    let pki = TestPki::new();

    let data = b"Hello, World!";

    // Create signer
    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");

    // Sign data
    let signature = signer.sign(data).expect("failed to sign");

    // Create verifier
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");

    // Verify signature
    let result = verifier.verify(&signature).expect("failed to verify");
    assert_eq!(result.content, data);
}

#[test]
fn test_verify_wrong_root() {
    let pki = TestPki::new();

    let data = b"Hello, World!";

    // Create signer
    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");

    // Sign data
    let signature = signer.sign(data).expect("failed to sign");

    // Create verifier with wrong root
    let verifier = CmsVerifier::new(&pki.other_root_cert_pem)
        .expect("failed to create verifier with wrong root");

    // Verification should fail
    let result = verifier.verify(&signature);
    assert!(result.is_err(), "verification should fail with wrong root");
}

#[test]
fn test_verify_content() {
    let pki = TestPki::new();

    let data = b"Hello, World!";

    // Create signer
    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");

    // Sign data
    let signature = signer.sign(data).expect("failed to sign");

    // Create verifier
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");

    // Verify content matches
    verifier
        .verify_content(&signature, data)
        .expect("verify_content should succeed");

    // Verify content mismatch is detected
    let result = verifier.verify_content(&signature, b"wrong data");
    assert!(
        result.is_err(),
        "verify_content should fail with wrong data"
    );
}

#[test]
fn test_openssl_interop_verify_our_signature() {
    let pki = TestPki::new();
    let dir = pki.temp_dir.path();

    let data = b"Hello from Rust!";

    // Create signer
    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");

    // Sign data
    let signature = signer.sign(data).expect("failed to sign");

    // Write signature to file
    let sig_path = dir.join("signature.cms");
    std::fs::write(&sig_path, &signature).expect("failed to write signature");

    // Write root cert
    let root_path = dir.join("root.crt");
    std::fs::write(&root_path, &pki.root_cert_pem).expect("failed to write root cert");

    // Verify with OpenSSL
    let output_path = dir.join("output.bin");
    let status = Command::new("openssl")
        .args(["cms", "-verify", "-in"])
        .arg(&sig_path)
        .args(["-inform", "DER", "-out"])
        .arg(&output_path)
        .args([
            "-no-CAfile",
            "-no-CApath",
            "-no-CAstore",
            "-verify_retcode",
            "-CAfile",
        ])
        .arg(&root_path)
        .status()
        .expect("failed to run openssl verify");

    assert!(
        status.success(),
        "OpenSSL should successfully verify our signature"
    );

    // Verify content matches
    let extracted = std::fs::read(&output_path).expect("failed to read output");
    assert_eq!(extracted, data, "extracted content should match");
}

#[test]
fn test_openssl_interop_sign_with_openssl() {
    let pki = TestPki::new();
    let dir = pki.temp_dir.path();

    let data = b"Hello from OpenSSL!";

    // Write data to file
    let data_path = dir.join("data.bin");
    std::fs::write(&data_path, data).expect("failed to write data");

    // Write keys
    let root_path = dir.join("root.crt");
    std::fs::write(&root_path, &pki.root_cert_pem).expect("failed to write root cert");

    let signer_cert_path = dir.join("signer.crt");
    std::fs::write(&signer_cert_path, &pki.signer_cert_pem).expect("failed to write signer cert");

    let signer_key_path = dir.join("signer.key");
    std::fs::write(&signer_key_path, &pki.signer_key_pem).expect("failed to write signer key");

    // Sign with OpenSSL
    let sig_path = dir.join("signature.cms");
    let status = Command::new("openssl")
        .args(["cms", "-sign", "-in"])
        .arg(&data_path)
        .args(["-signer"])
        .arg(&signer_cert_path)
        .args(["-inkey"])
        .arg(&signer_key_path)
        .args(["-out"])
        .arg(&sig_path)
        .args(["-outform", "DER", "-nosmimecap", "-nodetach", "-binary"])
        .status()
        .expect("failed to run openssl sign");

    assert!(
        status.success(),
        "OpenSSL should successfully sign the data"
    );

    // Read signature
    let signature = std::fs::read(&sig_path).expect("failed to read signature");

    // Verify with our library
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier
        .verify(&signature)
        .expect("failed to verify OpenSSL signature");
    assert_eq!(result.content, data, "content should match");
}

#[test]
fn test_signer_builder() {
    let pki = TestPki::new();

    let data = b"Builder test data";

    // Use builder API
    let signer = SignerBuilder::new(&pki.signer_cert_pem, &pki.signer_key_pem)
        .expect("failed to create builder")
        .build()
        .expect("failed to build signer");

    // Sign data
    let signature = signer.sign(data).expect("failed to sign");

    // Verify
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier.verify(&signature).expect("failed to verify");
    assert_eq!(result.content, data);
}

#[test]
fn test_large_data() {
    let pki = TestPki::new();

    // 1MB of data
    let data: Vec<u8> = (0..1024 * 1024).map(|i| (i % 256) as u8).collect();

    // Create signer
    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");

    // Sign data
    let signature = signer.sign(&data).expect("failed to sign large data");

    // Create verifier
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");

    // Verify signature
    let result = verifier
        .verify(&signature)
        .expect("failed to verify large data");
    assert_eq!(result.content, data);
}

#[test]
fn test_empty_data() {
    let pki = TestPki::new();

    let data = b"";

    // Create signer
    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");

    // Sign data
    let signature = signer.sign(data).expect("failed to sign empty data");

    // Create verifier
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");

    // Verify signature
    let result = verifier
        .verify(&signature)
        .expect("failed to verify empty data");
    assert_eq!(result.content, data.as_slice());
}

/// Test PKI with intermediate certificate.
struct TestPkiWithIntermediate {
    root_cert_pem: Vec<u8>,
    intermediate_cert_pem: Vec<u8>,
    signer_cert_pem: Vec<u8>,
    signer_key_pem: Vec<u8>,
    #[allow(dead_code)]
    temp_dir: tempfile::TempDir,
}

impl TestPkiWithIntermediate {
    fn new() -> Self {
        let temp_dir = tempfile::tempdir().expect("failed to create temp dir");
        let dir = temp_dir.path();

        // Generate root CA key and certificate (ECDSA P-256)
        let root_key_path = dir.join("root.key");
        let root_cert_path = dir.join("root.crt");

        let status = Command::new("openssl")
            .args([
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out",
            ])
            .arg(&root_key_path)
            .status()
            .expect("failed to generate root key");
        assert!(status.success());

        let status = Command::new("openssl")
            .args(["req", "-x509", "-new", "-key"])
            .arg(&root_key_path)
            .args(["-out"])
            .arg(&root_cert_path)
            .args(["-days", "3650", "-subj", "/CN=Test Root CA"])
            .status()
            .expect("failed to generate root cert");
        assert!(status.success());

        // Generate intermediate CA key and certificate
        let intermediate_key_path = dir.join("intermediate.key");
        let intermediate_csr_path = dir.join("intermediate.csr");
        let intermediate_cert_path = dir.join("intermediate.crt");

        let status = Command::new("openssl")
            .args([
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out",
            ])
            .arg(&intermediate_key_path)
            .status()
            .expect("failed to generate intermediate key");
        assert!(status.success());

        let status = Command::new("openssl")
            .args(["req", "-new", "-key"])
            .arg(&intermediate_key_path)
            .args(["-out"])
            .arg(&intermediate_csr_path)
            .args(["-subj", "/CN=Test Intermediate CA"])
            .status()
            .expect("failed to generate intermediate csr");
        assert!(status.success());

        let status = Command::new("openssl")
            .args(["x509", "-req", "-in"])
            .arg(&intermediate_csr_path)
            .args(["-CA"])
            .arg(&root_cert_path)
            .args(["-CAkey"])
            .arg(&root_key_path)
            .args(["-CAcreateserial", "-out"])
            .arg(&intermediate_cert_path)
            .args(["-days", "1825"])
            .status()
            .expect("failed to generate intermediate cert");
        assert!(status.success());

        // Generate signer key and certificate (signed by intermediate)
        let signer_key_path = dir.join("signer.key");
        let signer_csr_path = dir.join("signer.csr");
        let signer_cert_path = dir.join("signer.crt");

        let status = Command::new("openssl")
            .args([
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out",
            ])
            .arg(&signer_key_path)
            .status()
            .expect("failed to generate signer key");
        assert!(status.success());

        let status = Command::new("openssl")
            .args(["req", "-new", "-key"])
            .arg(&signer_key_path)
            .args(["-out"])
            .arg(&signer_csr_path)
            .args(["-subj", "/CN=Test Signer"])
            .status()
            .expect("failed to generate signer csr");
        assert!(status.success());

        let status = Command::new("openssl")
            .args(["x509", "-req", "-in"])
            .arg(&signer_csr_path)
            .args(["-CA"])
            .arg(&intermediate_cert_path)
            .args(["-CAkey"])
            .arg(&intermediate_key_path)
            .args(["-CAcreateserial", "-out"])
            .arg(&signer_cert_path)
            .args(["-days", "365"])
            .status()
            .expect("failed to generate signer cert");
        assert!(status.success());

        let root_cert_pem = std::fs::read(&root_cert_path).expect("failed to read root cert");
        let intermediate_cert_pem =
            std::fs::read(&intermediate_cert_path).expect("failed to read intermediate cert");
        let signer_cert_pem = std::fs::read(&signer_cert_path).expect("failed to read signer cert");
        let signer_key_pem = std::fs::read(&signer_key_path).expect("failed to read signer key");

        Self {
            root_cert_pem,
            intermediate_cert_pem,
            signer_cert_pem,
            signer_key_pem,
            temp_dir,
        }
    }
}

#[test]
fn test_certificate_chain_with_intermediate() {
    let pki = TestPkiWithIntermediate::new();

    let data = b"Data signed with intermediate cert chain";

    // Create signer with intermediate certificate
    let signer = SignerBuilder::new(&pki.signer_cert_pem, &pki.signer_key_pem)
        .expect("failed to create builder")
        .with_intermediate_cert(&pki.intermediate_cert_pem)
        .expect("failed to add intermediate cert")
        .build()
        .expect("failed to build signer");

    // Sign data
    let signature = signer.sign(data).expect("failed to sign");

    // Create verifier with root cert
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");

    // Verify signature - should work because intermediate cert is embedded
    let result = verifier.verify(&signature).expect("failed to verify");
    assert_eq!(result.content, data);

    // Certificate chain should include signer -> intermediate -> root
    assert_eq!(
        result.certificate_chain.len(),
        3,
        "chain should have 3 certs"
    );
}

/// Test PKI with RSA keys for RSA-PSS testing.
struct TestPkiRsa {
    root_cert_pem: Vec<u8>,
    signer_cert_pem: Vec<u8>,
    signer_key_pem: Vec<u8>,
    #[allow(dead_code)]
    temp_dir: tempfile::TempDir,
}

impl TestPkiRsa {
    fn new() -> Self {
        let temp_dir = tempfile::tempdir().expect("failed to create temp dir");
        let dir = temp_dir.path();

        // Generate root CA key and certificate (RSA 2048)
        let root_key_path = dir.join("root.key");
        let root_cert_path = dir.join("root.crt");

        let status = Command::new("openssl")
            .args(["genrsa", "-out"])
            .arg(&root_key_path)
            .args(["2048"])
            .status()
            .expect("failed to generate RSA root key");
        assert!(status.success());

        let status = Command::new("openssl")
            .args(["req", "-x509", "-new", "-key"])
            .arg(&root_key_path)
            .args(["-out"])
            .arg(&root_cert_path)
            .args(["-days", "3650", "-subj", "/CN=Test RSA Root CA"])
            .status()
            .expect("failed to generate RSA root cert");
        assert!(status.success());

        // Generate signer key and certificate (RSA, signed by root)
        let signer_key_path = dir.join("signer.key");
        let signer_csr_path = dir.join("signer.csr");
        let signer_cert_path = dir.join("signer.crt");

        let status = Command::new("openssl")
            .args(["genrsa", "-out"])
            .arg(&signer_key_path)
            .args(["2048"])
            .status()
            .expect("failed to generate RSA signer key");
        assert!(status.success());

        let status = Command::new("openssl")
            .args(["req", "-new", "-key"])
            .arg(&signer_key_path)
            .args(["-out"])
            .arg(&signer_csr_path)
            .args(["-subj", "/CN=Test RSA Signer"])
            .status()
            .expect("failed to generate RSA signer csr");
        assert!(status.success());

        let status = Command::new("openssl")
            .args(["x509", "-req", "-in"])
            .arg(&signer_csr_path)
            .args(["-CA"])
            .arg(&root_cert_path)
            .args(["-CAkey"])
            .arg(&root_key_path)
            .args(["-CAcreateserial", "-out"])
            .arg(&signer_cert_path)
            .args(["-days", "365"])
            .status()
            .expect("failed to generate RSA signer cert");
        assert!(status.success());

        let root_cert_pem = std::fs::read(&root_cert_path).expect("failed to read root cert");
        let signer_cert_pem = std::fs::read(&signer_cert_path).expect("failed to read signer cert");
        let signer_key_pem = std::fs::read(&signer_key_path).expect("failed to read signer key");

        Self {
            root_cert_pem,
            signer_cert_pem,
            signer_key_pem,
            temp_dir,
        }
    }
}

#[test]
fn test_rsa_pss_sign_and_verify() {
    let pki = TestPkiRsa::new();

    let data = b"RSA-PSS signed data";

    // Create signer with RSA-PSS mode
    let signer = SignerBuilder::new(&pki.signer_cert_pem, &pki.signer_key_pem)
        .expect("failed to create builder")
        .with_rsa_mode(RsaSignatureMode::Pss)
        .with_rsa_hash(RsaHashAlgorithm::Sha256)
        .build()
        .expect("failed to build signer");

    // Verify the algorithm is RSA-PSS
    assert_eq!(
        signer.algorithm(),
        rugix_pki::SignatureAlgorithm::RsaPssSha256
    );

    // Sign data
    let signature = signer.sign(data).expect("failed to sign with RSA-PSS");

    // Create verifier
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");

    // Verify signature
    let result = verifier
        .verify(&signature)
        .expect("failed to verify RSA-PSS signature");
    assert_eq!(result.content, data);
}

#[test]
fn test_rsa_pss_sha384() {
    let pki = TestPkiRsa::new();

    let data = b"RSA-PSS SHA-384 signed data";

    // Create signer with RSA-PSS + SHA-384
    let signer = SignerBuilder::new(&pki.signer_cert_pem, &pki.signer_key_pem)
        .expect("failed to create builder")
        .with_rsa_mode(RsaSignatureMode::Pss)
        .with_rsa_hash(RsaHashAlgorithm::Sha384)
        .build()
        .expect("failed to build signer");

    assert_eq!(
        signer.algorithm(),
        rugix_pki::SignatureAlgorithm::RsaPssSha384
    );

    // Sign and verify
    let signature = signer.sign(data).expect("failed to sign");
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier.verify(&signature).expect("failed to verify");
    assert_eq!(result.content, data);
}

#[test]
fn test_rsa_pss_sha512() {
    let pki = TestPkiRsa::new();

    let data = b"RSA-PSS SHA-512 signed data";

    // Create signer with RSA-PSS + SHA-512
    let signer = SignerBuilder::new(&pki.signer_cert_pem, &pki.signer_key_pem)
        .expect("failed to create builder")
        .with_rsa_mode(RsaSignatureMode::Pss)
        .with_rsa_hash(RsaHashAlgorithm::Sha512)
        .build()
        .expect("failed to build signer");

    assert_eq!(
        signer.algorithm(),
        rugix_pki::SignatureAlgorithm::RsaPssSha512
    );

    // Sign and verify
    let signature = signer.sign(data).expect("failed to sign");
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier.verify(&signature).expect("failed to verify");
    assert_eq!(result.content, data);
}

#[test]
fn test_rsa_pkcs1_default() {
    let pki = TestPkiRsa::new();

    let data = b"RSA PKCS#1 v1.5 signed data";

    // Create signer with default mode (PKCS#1 v1.5)
    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");

    // Default should be PKCS#1 v1.5 with SHA-256
    assert_eq!(
        signer.algorithm(),
        rugix_pki::SignatureAlgorithm::RsaPkcs1Sha256
    );

    // Sign and verify
    let signature = signer.sign(data).expect("failed to sign");
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier.verify(&signature).expect("failed to verify");
    assert_eq!(result.content, data);
}

/// Test PKI with Ed25519 keys.
struct TestPkiEd25519 {
    root_cert_pem: Vec<u8>,
    signer_cert_pem: Vec<u8>,
    signer_key_pem: Vec<u8>,
    #[allow(dead_code)]
    temp_dir: tempfile::TempDir,
}

impl TestPkiEd25519 {
    fn new() -> Self {
        let temp_dir = tempfile::tempdir().expect("failed to create temp dir");
        let dir = temp_dir.path();

        // Generate root CA key and certificate (Ed25519)
        let root_key_path = dir.join("root.key");
        let root_cert_path = dir.join("root.crt");

        let status = Command::new("openssl")
            .args(["genpkey", "-algorithm", "ED25519", "-out"])
            .arg(&root_key_path)
            .status()
            .expect("failed to generate Ed25519 root key");
        assert!(status.success(), "failed to generate Ed25519 root key");

        let status = Command::new("openssl")
            .args(["req", "-x509", "-new", "-key"])
            .arg(&root_key_path)
            .args(["-out"])
            .arg(&root_cert_path)
            .args(["-days", "3650", "-subj", "/CN=Test Ed25519 Root CA"])
            .status()
            .expect("failed to generate Ed25519 root cert");
        assert!(status.success(), "failed to generate Ed25519 root cert");

        // Generate signer key and certificate (Ed25519, signed by root)
        let signer_key_path = dir.join("signer.key");
        let signer_csr_path = dir.join("signer.csr");
        let signer_cert_path = dir.join("signer.crt");

        let status = Command::new("openssl")
            .args(["genpkey", "-algorithm", "ED25519", "-out"])
            .arg(&signer_key_path)
            .status()
            .expect("failed to generate Ed25519 signer key");
        assert!(status.success(), "failed to generate Ed25519 signer key");

        let status = Command::new("openssl")
            .args(["req", "-new", "-key"])
            .arg(&signer_key_path)
            .args(["-out"])
            .arg(&signer_csr_path)
            .args(["-subj", "/CN=Test Ed25519 Signer"])
            .status()
            .expect("failed to generate Ed25519 signer csr");
        assert!(status.success(), "failed to generate Ed25519 signer csr");

        let status = Command::new("openssl")
            .args(["x509", "-req", "-in"])
            .arg(&signer_csr_path)
            .args(["-CA"])
            .arg(&root_cert_path)
            .args(["-CAkey"])
            .arg(&root_key_path)
            .args(["-CAcreateserial", "-out"])
            .arg(&signer_cert_path)
            .args(["-days", "365"])
            .status()
            .expect("failed to generate Ed25519 signer cert");
        assert!(status.success(), "failed to generate Ed25519 signer cert");

        let root_cert_pem = std::fs::read(&root_cert_path).expect("failed to read root cert");
        let signer_cert_pem = std::fs::read(&signer_cert_path).expect("failed to read signer cert");
        let signer_key_pem = std::fs::read(&signer_key_path).expect("failed to read signer key");

        Self {
            root_cert_pem,
            signer_cert_pem,
            signer_key_pem,
            temp_dir,
        }
    }
}

#[test]
fn test_ed25519_sign_and_verify() {
    let pki = TestPkiEd25519::new();

    let data = b"Ed25519 signed data";

    // Create signer
    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");

    // Verify the algorithm is Ed25519
    assert_eq!(
        signer.algorithm(),
        rugix_pki::SignatureAlgorithm::Ed25519
    );

    // Sign data
    let signature = signer.sign(data).expect("failed to sign with Ed25519");

    // Create verifier
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");

    // Verify signature
    let result = verifier
        .verify(&signature)
        .expect("failed to verify Ed25519 signature");
    assert_eq!(result.content, data);
}

#[test]
fn test_ed25519_large_data() {
    let pki = TestPkiEd25519::new();

    // 1MB of data
    let data: Vec<u8> = (0..1024 * 1024).map(|i| (i % 256) as u8).collect();

    // Create signer
    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");

    // Sign data
    let signature = signer.sign(&data).expect("failed to sign large data with Ed25519");

    // Create verifier
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");

    // Verify signature
    let result = verifier
        .verify(&signature)
        .expect("failed to verify large Ed25519 signature");
    assert_eq!(result.content, data);
}
