[package]
name = "rugix-versioning"
description = "Version parsing and requirement matching for Rugix component metadata."
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
serde.workspace = true

[lints]
workspace = true
