#!/usr/bin/env bash
set -euo pipefail

if [[ "$(id -u)" -ne 0 ]]; then
    echo "run as root, for example: sudo bash $0" >&2
    exit 1
fi

if ! command -v apt-get >/dev/null 2>&1; then
    distro="unknown"
    if [[ -r /etc/os-release ]]; then
        . /etc/os-release
        distro="${PRETTY_NAME:-${ID:-unknown}}"
    fi
    echo "unsupported distro: ${distro}; this installer requires apt-get" >&2
    exit 1
fi

if ! command -v systemctl >/dev/null 2>&1; then
    echo "this installer requires systemd" >&2
    exit 1
fi

GITHUB_REPO="${RUGIX_GITHUB_REPO:-rugix/rugix}"
REQUESTED_RUGIX_VERSION="${1:-${RUGIX_VERSION:-v1}}"
RUGIX_DEB_VARIANT="${RUGIX_DEB_VARIANT:-musl}"

case "$(uname -m)" in
    x86_64|amd64) DEB_ARCH="amd64" ;;
    aarch64|arm64) DEB_ARCH="arm64" ;;
    armv7l|armv8l) DEB_ARCH="armhf" ;;
    *) echo "unsupported architecture: $(uname -m)" >&2; exit 1 ;;
esac

case "${RUGIX_DEB_VARIANT}" in
    musl|gnu) ;;
    *) echo "unsupported Debian package variant: ${RUGIX_DEB_VARIANT}" >&2; exit 1 ;;
esac

apt-get update
apt-get install -y ca-certificates curl jq

if ! command -v docker >/dev/null 2>&1; then
    curl -fsSL https://test.docker.com -o /tmp/install-docker.sh
    sh /tmp/install-docker.sh
fi

systemctl enable --now docker.service
docker compose version >/dev/null

install -d -m 755 /usr/libexec/rugix
cat >/usr/libexec/rugix/rugix-docker-runtime-components <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

COMPONENTS_DIR="${RUGIX_COMPONENTS_DIR:-/run/rugix/components}"
OUTPUT_FILE="${RUGIX_DOCKER_COMPONENT_FILE:-${COMPONENTS_DIR}/docker.toml}"

tmp=""

prepare_output_file() {
    local output_dir output_name
    output_dir="$(dirname "${OUTPUT_FILE}")"
    output_name="$(basename "${OUTPUT_FILE}")"
    mkdir -p "${output_dir}"
    tmp="$(mktemp "${output_dir}/.${output_name}.tmp.XXXXXX")"
}

cleanup() {
    if [[ -n "${tmp}" ]]; then
        rm -f "${tmp}"
    fi
}
trap cleanup EXIT

toml_escape() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

is_component_version() {
    [[ "$1" =~ ^[0-9]+(\.[0-9]+)*(-[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)*)?(\+[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)*)?$ ]]
}

normalize_component_version() {
    local version="${1#v}"
    if is_component_version "${version}"; then
        printf '%s\n' "${version}"
    fi
}

append_runtime_capability() {
    local id="$1"
    local raw_version="${2:-}"
    local version=""

    if [[ -n "${raw_version}" ]]; then
        version="$(normalize_component_version "${raw_version}" || true)"
    fi

    printf '\n[[provides]]\nid = "%s"\n' "${id}" >>"${tmp}"
    if [[ -n "${version}" ]]; then
        printf 'version = "%s"\n' "${version}" >>"${tmp}"
    elif [[ -n "${raw_version}" ]]; then
        printf 'value = "%s"\n' "$(toml_escape "${raw_version}")" >>"${tmp}"
    fi
}

docker_version="$(docker version --format '{{.Server.Version}}' 2>/dev/null || docker version --format '{{.Client.Version}}' 2>/dev/null || true)"
compose_available=0
compose_version=""
if docker compose version >/dev/null 2>&1; then
    compose_available=1
    compose_version="$(docker compose version --short 2>/dev/null || true)"
fi
docker_component_version="$(normalize_component_version "${docker_version}" || true)"

if [[ -z "${docker_version}" && "${compose_available}" != "1" ]]; then
    rm -f "${OUTPUT_FILE}"
    exit 0
fi

prepare_output_file

cat >"${tmp}" <<EOF_COMPONENT
# Generated by rugix-docker-runtime-components. Do not edit.
id = "runtime.docker"
EOF_COMPONENT

if [[ -n "${docker_component_version}" ]]; then
    printf 'version = "%s"\n' "${docker_component_version}" >>"${tmp}"
elif [[ -n "${docker_version}" ]]; then
    append_runtime_capability "runtime.docker" "${docker_version}"
fi

if [[ "${compose_available}" == "1" ]]; then
    append_runtime_capability "runtime.docker-compose" "${compose_version}"
fi

chmod 0644 "${tmp}"
mv "${tmp}" "${OUTPUT_FILE}"
tmp=""
EOF
chmod 755 /usr/libexec/rugix/rugix-docker-runtime-components

cat >/etc/systemd/system/rugix-docker-runtime-components.service <<'EOF'
[Unit]
Description=Publish Docker runtime component metadata for Rugix
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
ExecStart=/usr/libexec/rugix/rugix-docker-runtime-components

[Install]
WantedBy=multi-user.target
EOF

resolve_rugix_version() {
    local requested="$1"
    local api="https://api.github.com/repos/${GITHUB_REPO}/releases"
    if [[ "${requested}" == "latest" ]]; then
        curl -fsSL "${api}?per_page=100" \
            | jq -r \
                '[.[] | select((.draft | not) and (.prerelease | not))]
                 | sort_by(.published_at)
                 | last
                 | .tag_name'
    elif [[ "${requested}" =~ ^v[0-9]+$ ]]; then
        curl -fsSL "${api}?per_page=100" \
            | jq -r --arg prefix "${requested}." \
                '[.[] | select((.draft | not) and (.prerelease | not) and (.tag_name | startswith($prefix)))]
                 | sort_by(.published_at)
                 | last
                 | .tag_name'
    else
        echo "${requested}"
    fi
}

release_tag_to_deb_version() {
    local version="${1#v}"
    if [[ "${version}" == *-* ]]; then
        local base="${version%%-*}"
        local rest="${version#*-}"
        version="${base}+${rest//-/.}"
    fi
    echo "${version}"
}

RUGIX_VERSION="$(resolve_rugix_version "${REQUESTED_RUGIX_VERSION}")"
if [[ -z "${RUGIX_VERSION}" || "${RUGIX_VERSION}" == "null" ]]; then
    echo "unable to resolve Rugix release version" >&2
    exit 1
fi

tmpdir="$(mktemp -d)"
trap 'rm -rf "${tmpdir}"' EXIT
deb_version="$(release_tag_to_deb_version "${RUGIX_VERSION}")"
package="rugix-ctrl-${RUGIX_DEB_VARIANT}"
deb="${tmpdir}/${package}_${deb_version}_${DEB_ARCH}.deb"
url="https://github.com/${GITHUB_REPO}/releases/download/${RUGIX_VERSION}/${package}_${deb_version}_${DEB_ARCH}.deb"
echo "downloading ${url}"
curl -fL "${url}" -o "${deb}"
apt-get install -y "${deb}"

cat >/etc/systemd/system/rugix-apps-restore-units.service <<'EOF'
[Unit]
Description=Restore Rugix app units into systemd
After=local-fs.target
DefaultDependencies=no

[Service]
Type=oneshot
ExecStart=/usr/bin/rugix-ctrl apps service-manager systemd restore-units
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

cat >/etc/systemd/system/rugix-apps-recover.service <<'EOF'
[Unit]
Description=Recover interrupted Rugix app transitions
After=multi-user.target rugix-apps-restore-units.service docker.service rugix-docker-runtime-components.service
Wants=rugix-apps-restore-units.service rugix-docker-runtime-components.service

[Service]
Type=oneshot
ExecStart=/usr/bin/rugix-ctrl apps recover
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now rugix-docker-runtime-components.service
systemctl enable --now rugix-apps-restore-units.service
systemctl enable --now rugix-apps-recover.service

rugix-ctrl --version
cat <<'EOF'

Rugix Ctrl Apps runtime is installed.

Next steps:
  Install a Rugix app bundle:
    rugix-ctrl apps install --bundle-hash "$(cat app.rugixb-hash)" app.rugixb

  Inspect installed apps:
    rugix-ctrl apps list
EOF
